project_id = "ilkrqlxrqaelflslbdnx"

[functions.setup-admin]
verify_jwt = false

[functions.import-employees]
verify_jwt = false

[functions.atc-assignments]
verify_jwt = false

[functions.fetch-roster]
verify_jwt = false

[functions.sync-roster]
verify_jwt = false

[functions.sync-leave-records]
verify_jwt = false

[functions.expire-records]
verify_jwt = false

[functions.fetch-schedule]
verify_jwt = false