/**
 * Golden fixtures — every row of the "Training status check" workbook as
 * exported on 2026-08-11, joined on (emp_id, unit).
 *
 * GENERATED FILE. Regenerate from a fresh export rather than hand-editing.
 *
 * `sheetDeadline` and `sheetDaysLeft` are the spreadsheet's own computed
 * columns and act as the oracle: our engine must reproduce them, because they
 * are what the training section works from today.
 *
 * `sheetHoursLeftDisplay` is the spreadsheet's "Hours left" column, which is
 * formatted `h:mm` instead of `[h]:mm` and therefore wraps at 24 hours. It is
 * kept here as a NEGATIVE oracle: the test asserts we do *not* reproduce it.
 */

export interface OjtFixtureRow {
    name: string;
    empId: string;
    unit: string;
    input: {
        requiredHours: number;
        requiredDays: number;
        performedHours: number;
        performedDays: number;
        startDate: string | null;
    };
    sheetDeadline: string | null;
    sheetDaysLeft: number;
    sheetHoursLeftDisplay: number;
}

/** The date the workbook was exported and its Days-left column evaluated. */
export const FIXTURE_TODAY = '2026-08-11';

/**
 * The sole row where our deadline intentionally differs from the sheet.
 * A 10-hour cycle is 0.667 months; the sheet's EDATE truncates that to 0 months
 * and returns 2026-06-16 for an OJT starting 2026-06-17 — a deadline one day
 * before the start. We return 2026-07-06.
 */
export const FRACTIONAL_MONTH_EXCEPTION = { empId: '10015621', unit: 'ACC+ACC(S)' };

export const OJT_FIXTURES: OjtFixtureRow[] = [
    {
        name: "AAKASH KUMAR",
        empId: "10023136",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 86.5,
            performedDays: 191,
            startDate: "2025-12-30",
        },
        sheetDeadline: "2026-04-29",
        sheetDaysLeft: -104,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "ABHISHEK KUMAR",
        empId: "10021938",
        unit: "ADC",
        input: {
            requiredHours: 75,
            requiredDays: 40,
            performedHours: 86.25,
            performedDays: 206,
            startDate: "2025-12-31",
        },
        sheetDeadline: "2026-05-30",
        sheetDaysLeft: -73,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "ABHISHEK MONDAL",
        empId: "10021023",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-22",
        },
        sheetDeadline: "2027-01-21",
        sheetDaysLeft: 163,
        sheetHoursLeftDisplay: 18,
    },
    {
        name: "ABHISHEK MUKHERJEE",
        empId: "10024032",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 58.5,
            performedDays: 96,
            startDate: "2026-05-01",
        },
        sheetDeadline: "2026-10-31",
        sheetDaysLeft: 81,
        sheetHoursLeftDisplay: 31.5,
    },
    {
        name: "ABHISHEK SHARMA",
        empId: "10021723",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-04-08",
        },
        sheetDeadline: "2026-10-07",
        sheetDaysLeft: 57,
        sheetHoursLeftDisplay: 18,
    },
    {
        name: "ADITYA KUMAR SINGH",
        empId: "10020256",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 223.83,
            performedDays: 340,
            startDate: "2025-07-29",
        },
        sheetDeadline: "2026-07-28",
        sheetDaysLeft: -14,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "AJEET KUMAR SINGH",
        empId: "10002472",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 172.17,
            performedDays: 186,
            startDate: "2026-01-25",
        },
        sheetDeadline: "2027-03-24",
        sheetDaysLeft: 225,
        sheetHoursLeftDisplay: 37.83,
    },
    {
        name: "AKASH CHOUDHURY",
        empId: "10009714",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 11,
            performedDays: 26,
            startDate: "2026-07-09",
        },
        sheetDeadline: "2027-01-08",
        sheetDaysLeft: 150,
        sheetHoursLeftDisplay: 7,
    },
    {
        name: "AKASH PANJA",
        empId: "10003862",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 40.67,
            performedDays: 48,
            startDate: "2026-06-19",
        },
        sheetDeadline: "2027-06-18",
        sheetDaysLeft: 311,
        sheetHoursLeftDisplay: 139.33,
    },
    {
        name: "AKSHIT GOYAL",
        empId: "10023104",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 87.08,
            performedDays: 191,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "ALOK SRIVASTAV",
        empId: "10021025",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-26",
        },
        sheetDeadline: "2026-08-25",
        sheetDaysLeft: 14,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "AMIT KISHORE",
        empId: "10021111",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 12.75,
            performedDays: 26,
            startDate: "2026-05-13",
        },
        sheetDeadline: "2026-11-12",
        sheetDaysLeft: 93,
        sheetHoursLeftDisplay: 5.25,
    },
    {
        name: "ANIMESH ADHIKARI",
        empId: "10022052",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "ANIMESH KUMAR",
        empId: "10023447",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "APOORV KUSHWAHA",
        empId: "10023192",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 75.75,
            performedDays: 128,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "APSHAY KUMAR",
        empId: "10023158",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 63.5,
            performedDays: 127,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "ARCHIT KUMAR",
        empId: "10023870",
        unit: "ADC",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 52.25,
            performedDays: 92,
            startDate: "2026-05-05",
        },
        sheetDeadline: "2026-09-04",
        sheetDaysLeft: 24,
        sheetHoursLeftDisplay: 7.75,
    },
    {
        name: "ARUN KUMAR",
        empId: "10023424",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-05",
        },
        sheetDeadline: "2026-09-04",
        sheetDaysLeft: 24,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "ASHISH KUMAR",
        empId: "10023109",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "ATUL SINGH",
        empId: "10002979",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2025-11-11",
        },
        sheetDeadline: "2026-02-10",
        sheetDaysLeft: -182,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "AVINASH",
        empId: "10020170",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 225,
            performedDays: 300,
            startDate: "2025-10-09",
        },
        sheetDeadline: "2026-12-08",
        sheetDaysLeft: 119,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "AVNISH KUMAR",
        empId: "10022059",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2025-08-18",
        },
        sheetDeadline: "2026-02-17",
        sheetDaysLeft: -175,
        sheetHoursLeftDisplay: 18,
    },
    {
        name: "AYAN DASTIDAR",
        empId: "10023446",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 2.75,
            performedDays: 3,
            startDate: "2026-07-30",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 9.25,
    },
    {
        name: "BHASKAR BISWAS",
        empId: "10010261",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 22.5,
            performedDays: 17,
            startDate: "2026-07-14",
        },
        sheetDeadline: "2026-10-13",
        sheetDaysLeft: 63,
        sheetHoursLeftDisplay: 22.5,
    },
    {
        name: "BHUPENDRA KUMAR GUPTA",
        empId: "10002977",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 45,
            performedDays: 44,
            startDate: "2026-01-14",
        },
        sheetDeadline: "2026-04-13",
        sheetDaysLeft: -120,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "BIJAN KUMAR BHAT",
        empId: "10015621",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 10,
            requiredDays: 5,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-06-17",
        },
        sheetDeadline: "2026-06-16",
        sheetDaysLeft: -56,
        sheetHoursLeftDisplay: 10,
    },
    {
        name: "BIKRAM MONDAL",
        empId: "10023669",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "CHANDAN PATHAK",
        empId: "10023608",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "CHANDRA MOHAN KUMAR PASWAN",
        empId: "10015589",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-02-24",
        },
        sheetDeadline: "2026-05-23",
        sheetDaysLeft: -80,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "DAVID TOPNO",
        empId: "10005102",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 29,
            performedDays: 52,
            startDate: "2026-06-10",
        },
        sheetDeadline: "2026-12-09",
        sheetDaysLeft: 120,
        sheetHoursLeftDisplay: 61,
    },
    {
        name: "DEBASHISH HANSDAH",
        empId: "10020257",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-02-24",
        },
        sheetDeadline: "2026-05-23",
        sheetDaysLeft: -80,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "DEEPAK KUMAR",
        empId: "10002347",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 3,
            performedHours: 183.33,
            performedDays: 215,
            startDate: "2026-01-02",
        },
        sheetDeadline: "2027-01-01",
        sheetDaysLeft: 143,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "DHEERAJ KUMAR",
        empId: "10023201",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 98,
            performedDays: 191,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "DIBAKAR MITRA",
        empId: "10001911",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 78.92,
            performedDays: 99,
            startDate: "2026-04-28",
        },
        sheetDeadline: "2026-08-27",
        sheetDaysLeft: 16,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "DINESH",
        empId: "10023094",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 80.75,
            performedDays: 191,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "DIPTARGHA BAUL",
        empId: "10003915",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 101,
            performedDays: 105,
            startDate: "2026-03-28",
        },
        sheetDeadline: "2027-05-27",
        sheetDaysLeft: 289,
        sheetHoursLeftDisplay: 109,
    },
    {
        name: "DIVYA DEV",
        empId: "10024181",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 22.5,
            performedDays: 44,
            startDate: "2026-06-21",
        },
        sheetDeadline: "2026-12-20",
        sheetDaysLeft: 131,
        sheetHoursLeftDisplay: 19.5,
    },
    {
        name: "DRONESH GAUTAM",
        empId: "10023095",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 92,
            performedDays: 151,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "DURGESH CHANDRA TRIPATHI",
        empId: "10002405",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 5,
            performedDays: 2,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2027-07-30",
        sheetDaysLeft: 353,
        sheetHoursLeftDisplay: 7,
    },
    {
        name: "GANESH SHANKAR VIDYARTHI",
        empId: "10003609",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 76,
            performedDays: 57,
            startDate: "2026-04-27",
        },
        sheetDeadline: "2027-06-26",
        sheetDaysLeft: 319,
        sheetHoursLeftDisplay: 134,
    },
    {
        name: "GAUTAM KUMAR",
        empId: "10002227",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 239.08,
            performedDays: 266,
            startDate: "2025-11-11",
        },
        sheetDeadline: "2027-01-10",
        sheetDaysLeft: 152,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "GOPAL JEE",
        empId: "10003848",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 46.08,
            performedDays: 35,
            startDate: "2026-07-01",
        },
        sheetDeadline: "2027-08-31",
        sheetDaysLeft: 385,
        sheetHoursLeftDisplay: 163.92,
    },
    {
        name: "HAIMANTI SENGUPTA",
        empId: "10003782",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 15.33,
            performedDays: 11,
            startDate: "2026-04-15",
        },
        sheetDeadline: "2027-06-14",
        sheetDaysLeft: 307,
        sheetHoursLeftDisplay: 2.67,
    },
    {
        name: "HARSH VISHWAKARMA",
        empId: "10023514",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 43.75,
            performedDays: 50,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 16.25,
    },
    {
        name: "HITESH RATHORE",
        empId: "10020143",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "IBOTOMBA NINGTHOUJAM",
        empId: "10001051",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 214.58,
            performedDays: 241,
            startDate: "2025-12-04",
        },
        sheetDeadline: "2027-02-03",
        sheetDaysLeft: 176,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "JAI OM UPADHYAY",
        empId: "10025441",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 90,
            performedHours: 19,
            performedDays: 31,
            startDate: "2026-07-02",
        },
        sheetDeadline: "2027-01-01",
        sheetDaysLeft: 143,
        sheetHoursLeftDisplay: 23,
    },
    {
        name: "JUSTIN MINJ",
        empId: "10015614",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-03-03",
        },
        sheetDeadline: "2026-06-02",
        sheetDaysLeft: -70,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "JYOTIRMOY GUHA",
        empId: "10003899",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 143.33,
            performedDays: 128,
            startDate: "2026-03-29",
        },
        sheetDeadline: "2027-05-28",
        sheetDaysLeft: 290,
        sheetHoursLeftDisplay: 66.67,
    },
    {
        name: "K IBUNGOTON SINGHA",
        empId: "10017314",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 62.5,
            performedDays: 235,
            startDate: "2025-08-11",
        },
        sheetDeadline: "2025-11-10",
        sheetDaysLeft: -274,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "KAUSHAL KAMAL",
        empId: "10002046",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 52,
            performedDays: 71,
            startDate: "2026-05-29",
        },
        sheetDeadline: "2026-11-28",
        sheetDaysLeft: 109,
        sheetHoursLeftDisplay: 38,
    },
    {
        name: "KUMAR ABHIJIT",
        empId: "10003965",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 235.92,
            performedDays: 202,
            startDate: "2026-01-15",
        },
        sheetDeadline: "2027-03-14",
        sheetDaysLeft: 215,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "KUMAR SAURAV",
        empId: "10023371",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "LAL BAHADUR KUMAR",
        empId: "10003911",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 3.5,
            performedDays: 4,
            startDate: "2026-06-22",
        },
        sheetDeadline: "2026-09-21",
        sheetDaysLeft: 41,
        sheetHoursLeftDisplay: 17.5,
    },
    {
        name: "MADHURIMA HALDER",
        empId: "10023179",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 78,
            performedDays: 171,
            startDate: "2025-12-30",
        },
        sheetDeadline: "2026-04-29",
        sheetDaysLeft: -104,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MANIDEEPA ROY",
        empId: "10023347",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "MANIK CHANDRA KARMAKAR",
        empId: "10024184",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 90,
            performedHours: 52.25,
            performedDays: 85,
            startDate: "2026-05-12",
        },
        sheetDeadline: "2026-11-11",
        sheetDaysLeft: 92,
        sheetHoursLeftDisplay: 37.75,
    },
    {
        name: "MANISH AGARWAL",
        empId: "10001141",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 48.75,
            performedDays: 232,
            startDate: "2025-08-18",
        },
        sheetDeadline: "2025-11-17",
        sheetDaysLeft: -267,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MANISH KUMAR",
        empId: "10021729",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 219.42,
            performedDays: 362,
            startDate: "2025-08-03",
        },
        sheetDeadline: "2026-08-02",
        sheetDaysLeft: -9,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MANISH KUMAR",
        empId: "10023483",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-07",
        },
        sheetDeadline: "2026-09-06",
        sheetDaysLeft: 26,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "MANOJ KUMAR YADAV",
        empId: "10002911",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 30,
            requiredDays: 15,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-06-17",
        },
        sheetDeadline: "2026-08-16",
        sheetDaysLeft: 5,
        sheetHoursLeftDisplay: 6,
    },
    {
        name: "MAYANK KUMAR",
        empId: "10023398",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "MD SHAQUIB ANSARI",
        empId: "10023410",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 32.25,
            performedDays: 60,
            startDate: "2026-05-05",
        },
        sheetDeadline: "2026-09-04",
        sheetDaysLeft: 24,
        sheetHoursLeftDisplay: 27.75,
    },
    {
        name: "MEENA KUMARI",
        empId: "10020412",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 120,
            requiredDays: 60,
            performedHours: 203.25,
            performedDays: 293,
            startDate: "2025-10-09",
        },
        sheetDeadline: "2026-06-08",
        sheetDaysLeft: -64,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MELBIN PHILIP VARGHESE",
        empId: "10003937",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 21.5,
            performedDays: 25,
            startDate: "2026-07-09",
        },
        sheetDeadline: "2027-07-08",
        sheetDaysLeft: 331,
        sheetHoursLeftDisplay: 14.5,
    },
    {
        name: "MILAN KANTI MANDAL",
        empId: "10012533",
        unit: "PLR",
        input: {
            requiredHours: 15,
            requiredDays: 7,
            performedHours: 16.75,
            performedDays: 39,
            startDate: "2026-06-11",
        },
        sheetDeadline: "2026-07-10",
        sheetDaysLeft: -32,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MOHAMMAD SULTAN",
        empId: "10023075",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 85.33,
            performedDays: 191,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "MOHIT KUMAR",
        empId: "10003900",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 17,
            performedDays: 15,
            startDate: "2026-06-16",
        },
        sheetDeadline: "2026-09-15",
        sheetDaysLeft: 35,
        sheetHoursLeftDisplay: 4,
    },
    {
        name: "MOUMITA SARCAR",
        empId: "10003821",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 84.5,
            performedDays: 107,
            startDate: "2026-02-24",
        },
        sheetDeadline: "2026-06-23",
        sheetDaysLeft: -49,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "NAGMANI KUMAR",
        empId: "10003864",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-26",
        },
        sheetDeadline: "2026-08-25",
        sheetDaysLeft: 14,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "NAVITA PRAVEEN SEHGAL",
        empId: "10003218",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 142.75,
            performedDays: 231,
            startDate: "2025-08-29",
        },
        sheetDeadline: "2026-02-27",
        sheetDaysLeft: -165,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "NEERAJ KUMAR MAHESH",
        empId: "10023364",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "NISHESH SHUKLA",
        empId: "10002833",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 72.5,
            performedDays: 252,
            startDate: "2025-08-11",
        },
        sheetDeadline: "2025-11-10",
        sheetDaysLeft: -274,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "PRABHAT RANJAN",
        empId: "10002471",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 15,
            performedDays: 29,
            startDate: "2026-07-07",
        },
        sheetDeadline: "2027-01-06",
        sheetDaysLeft: 148,
        sheetHoursLeftDisplay: 3,
    },
    {
        name: "PRAKASH CHANDRA MISHRA",
        empId: "10012191",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 235.5,
            performedDays: 454,
            startDate: "2024-12-05",
        },
        sheetDeadline: "2026-02-04",
        sheetDaysLeft: -188,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "PRAKASH KUMAR",
        empId: "10023395",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "PRATICK DASGUPTA",
        empId: "10002317",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 170.5,
            performedDays: 205,
            startDate: "2026-01-12",
        },
        sheetDeadline: "2027-03-11",
        sheetDaysLeft: 212,
        sheetHoursLeftDisplay: 39.5,
    },
    {
        name: "PRIYA RANJAN",
        empId: "10023526",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "PRIYABRATA PAN",
        empId: "10023452",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 49,
            performedDays: 57,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 11,
    },
    {
        name: "RAHUL KUMAR",
        empId: "10003838",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 176.75,
            performedDays: 201,
            startDate: "2026-01-13",
        },
        sheetDeadline: "2027-03-12",
        sheetDaysLeft: 213,
        sheetHoursLeftDisplay: 33.25,
    },
    {
        name: "RAJ KUMAR",
        empId: "10022258",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 276.83,
            performedDays: 271,
            startDate: "2025-10-29",
        },
        sheetDeadline: "2026-12-28",
        sheetDaysLeft: 139,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "RAJAT SHRIVASTAVA",
        empId: "10004045",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 213.33,
            performedDays: 203,
            startDate: "2026-01-08",
        },
        sheetDeadline: "2027-03-07",
        sheetDaysLeft: 208,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "RATNAKAR PRATAP SINGH",
        empId: "10002348",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 227.83,
            performedDays: 254,
            startDate: "2025-10-27",
        },
        sheetDeadline: "2026-12-26",
        sheetDaysLeft: 137,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "RAUSHAN KUMAR",
        empId: "10023379",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "RAVI BHUSHAN",
        empId: "10003967",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 156.25,
            performedDays: 209,
            startDate: "2026-01-05",
        },
        sheetDeadline: "2027-01-04",
        sheetDaysLeft: 146,
        sheetHoursLeftDisplay: 23.75,
    },
    {
        name: "RAVI KUMAR",
        empId: "10002458",
        unit: "ACC",
        input: {
            requiredHours: 120,
            requiredDays: 60,
            performedHours: 82.75,
            performedDays: 247,
            startDate: "2025-06-09",
        },
        sheetDeadline: "2026-02-08",
        sheetDaysLeft: -184,
        sheetHoursLeftDisplay: 37.25,
    },
    {
        name: "RAVI SHANKAR KUMAR",
        empId: "10021365",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 190.92,
            performedDays: 223,
            startDate: "2025-10-24",
        },
        sheetDeadline: "2026-12-23",
        sheetDaysLeft: 134,
        sheetHoursLeftDisplay: 19.08,
    },
    {
        name: "RICHA SINGH",
        empId: "10002195",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 50.67,
            performedDays: 30,
            startDate: "2026-07-07",
        },
        sheetDeadline: "2027-09-06",
        sheetDaysLeft: 391,
        sheetHoursLeftDisplay: 159.33,
    },
    {
        name: "RISHABH",
        empId: "10023390",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 49.75,
            performedDays: 77,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 10.25,
    },
    {
        name: "RITESH SINGH RATHOUR",
        empId: "10023209",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 80.75,
            performedDays: 127,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "ROSHAN PRASAD",
        empId: "10023639",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "RUDRA PRATAP",
        empId: "10003134",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 130.83,
            performedDays: 243,
            startDate: "2025-10-20",
        },
        sheetDeadline: "2026-04-19",
        sheetDaysLeft: -114,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "RUDRA PRATAP",
        empId: "10003134",
        unit: "ADC",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-06-29",
        },
        sheetDeadline: "2026-10-28",
        sheetDaysLeft: 78,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "RUPESH KUMAR",
        empId: "10023236",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 78.5,
            performedDays: 136,
            startDate: "2026-01-15",
        },
        sheetDeadline: "2026-05-14",
        sheetDaysLeft: -89,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SAGNIK MONDAL",
        empId: "10023348",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "SANDEEP KUMAR GUPTA",
        empId: "10002574",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 216.58,
            performedDays: 332,
            startDate: "2025-07-22",
        },
        sheetDeadline: "2026-07-21",
        sheetDaysLeft: -21,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SANJAY KUMAR",
        empId: "10023093",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 92.08,
            performedDays: 185,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SANJEEV RANJAN PRASAD",
        empId: "10013449",
        unit: "PLR",
        input: {
            requiredHours: 15,
            requiredDays: 7,
            performedHours: 19.25,
            performedDays: 22,
            startDate: "2026-07-08",
        },
        sheetDeadline: "2026-08-07",
        sheetDaysLeft: -4,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SANJOY DEB BARMAN",
        empId: "10022080",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-04-01",
        },
        sheetDeadline: "2026-09-30",
        sheetDaysLeft: 50,
        sheetHoursLeftDisplay: 18,
    },
    {
        name: "SANMITRA BHOWMIK",
        empId: "10021133",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 76.75,
            performedDays: 111,
            startDate: "2026-04-16",
        },
        sheetDeadline: "2026-10-15",
        sheetDaysLeft: 65,
        sheetHoursLeftDisplay: 13.25,
    },
    {
        name: "SANTOSH KUMAR",
        empId: "10020147",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 205.33,
            performedDays: 167,
            startDate: "2026-02-16",
        },
        sheetDeadline: "2027-04-15",
        sheetDaysLeft: 247,
        sheetHoursLeftDisplay: 4.67,
    },
    {
        name: "SAYAN GAYEN",
        empId: "10021915",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "SHALINI SINGH",
        empId: "10023586",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 3,
            performedDays: 7,
            startDate: "2026-07-29",
        },
        sheetDeadline: "2027-01-28",
        sheetDaysLeft: 170,
        sheetHoursLeftDisplay: 15,
    },
    {
        name: "SHREEKRUSHNA MISHRA",
        empId: "10023432",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-06",
        },
        sheetDeadline: "2026-09-05",
        sheetDaysLeft: 25,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "SHRUTI KUMARI",
        empId: "10023435",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 7,
            performedDays: 21,
            startDate: "2026-05-07",
        },
        sheetDeadline: "2026-09-06",
        sheetDaysLeft: 26,
        sheetHoursLeftDisplay: 5,
    },
    {
        name: "SHUBHAM RAJ",
        empId: "10023143",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 84,
            performedDays: 128,
            startDate: "2025-12-30",
        },
        sheetDeadline: "2026-04-29",
        sheetDaysLeft: -104,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SHUBHAM SWARAJ",
        empId: "10025385",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 90,
            performedHours: 11,
            performedDays: 14,
            startDate: "2026-07-22",
        },
        sheetDeadline: "2027-01-21",
        sheetDaysLeft: 163,
        sheetHoursLeftDisplay: 7,
    },
    {
        name: "SHUVASMITA ROY",
        empId: "10003863",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 24.5,
            performedDays: 20,
            startDate: "2026-07-01",
        },
        sheetDeadline: "2027-08-31",
        sheetDaysLeft: 385,
        sheetHoursLeftDisplay: 185.5,
    },
    {
        name: "SIDDHANT BHUSHAN",
        empId: "10023873",
        unit: "ADC",
        input: {
            requiredHours: 75,
            requiredDays: 40,
            performedHours: 77.17,
            performedDays: 124,
            startDate: "2026-04-03",
        },
        sheetDeadline: "2026-09-02",
        sheetDaysLeft: 22,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SIDDHAYAK SANYAL",
        empId: "10021871",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 46.67,
            performedDays: 106,
            startDate: "2026-04-21",
        },
        sheetDeadline: "2026-10-20",
        sheetDaysLeft: 70,
        sheetHoursLeftDisplay: 43.33,
    },
    {
        name: "SOMA MONDAL",
        empId: "10024279",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 90,
            performedHours: 96.92,
            performedDays: 205,
            startDate: "2026-01-10",
        },
        sheetDeadline: "2026-07-09",
        sheetDaysLeft: -33,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SOMNATH PATHAK",
        empId: "10024217",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 63,
            performedDays: 87,
            startDate: "2026-05-07",
        },
        sheetDeadline: "2026-11-06",
        sheetDaysLeft: 87,
        sheetHoursLeftDisplay: 27,
    },
    {
        name: "SOUMIK SENAPATI",
        empId: "10003963",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 50.5,
            performedDays: 39,
            startDate: "2026-06-26",
        },
        sheetDeadline: "2027-06-25",
        sheetDaysLeft: 318,
        sheetHoursLeftDisplay: 129.5,
    },
    {
        name: "SOUVIK DUTTA",
        empId: "10002572",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 35.5,
            performedDays: 35,
            startDate: "2026-07-01",
        },
        sheetDeadline: "2026-10-31",
        sheetDaysLeft: 81,
        sheetHoursLeftDisplay: 24.5,
    },
    {
        name: "SUBHAM PARASRAMKA",
        empId: "10023216",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 89.5,
            performedDays: 197,
            startDate: "2025-12-18",
        },
        sheetDeadline: "2026-04-17",
        sheetDaysLeft: -116,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SUBHAN DEY",
        empId: "10010227",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 180,
            performedHours: 18.83,
            performedDays: 84,
            startDate: "2026-05-07",
        },
        sheetDeadline: "2027-05-06",
        sheetDaysLeft: 268,
        sheetHoursLeftDisplay: 17.17,
    },
    {
        name: "SUBHOJIT PAL",
        empId: "10023349",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 37,
            performedDays: 67,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 23,
    },
    {
        name: "SUJIT KUMAR ROY",
        empId: "10012601",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 0,
            performedDays: 0,
            startDate: "2025-08-18",
        },
        sheetDeadline: "2025-11-17",
        sheetDaysLeft: -267,
        sheetHoursLeftDisplay: 21,
    },
    {
        name: "SULAGNA BHATTACHARYYA",
        empId: "10004010",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 49,
            performedDays: 38,
            startDate: "2026-06-26",
        },
        sheetDeadline: "2027-08-25",
        sheetDaysLeft: 379,
        sheetHoursLeftDisplay: 161,
    },
    {
        name: "SUMIT KUMAR TIWARI",
        empId: "10002193",
        unit: "APP+APP(S)",
        input: {
            requiredHours: 180,
            requiredDays: 90,
            performedHours: 189,
            performedDays: 274,
            startDate: "2025-10-29",
        },
        sheetDeadline: "2026-10-28",
        sheetDaysLeft: 78,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "SYED SHARIF ALAM",
        empId: "10021205",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 49,
            performedDays: 105,
            startDate: "2026-04-21",
        },
        sheetDeadline: "2026-10-20",
        sheetDaysLeft: 70,
        sheetHoursLeftDisplay: 41,
    },
    {
        name: "TAHSEEN RAZA",
        empId: "10023538",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "TANYA PRAKASH",
        empId: "10023690",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "TEKCHAM SHYAMKUMAR SINGH",
        empId: "10018898",
        unit: "OCC",
        input: {
            requiredHours: 45,
            requiredDays: 25,
            performedHours: 40,
            performedDays: 50,
            startDate: "2025-08-26",
        },
        sheetDeadline: "2025-11-25",
        sheetDaysLeft: -259,
        sheetHoursLeftDisplay: 5,
    },
    {
        name: "UDAY KESHRI",
        empId: "10023288",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 86.25,
            performedDays: 171,
            startDate: "2025-12-30",
        },
        sheetDeadline: "2026-04-29",
        sheetDaysLeft: -104,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "UJJWAL KUMAR",
        empId: "10023250",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "VIJAY KUMAR GUPTA",
        empId: "10013564",
        unit: "OCC",
        input: {
            requiredHours: 30,
            requiredDays: 15,
            performedHours: 33.33,
            performedDays: 16,
            startDate: "2026-07-11",
        },
        sheetDeadline: "2026-09-10",
        sheetDaysLeft: 30,
        sheetHoursLeftDisplay: 0,
    },
    {
        name: "VIKASH MISHRA",
        empId: "10023567",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "VISHAL JAISWAL",
        empId: "10009953",
        unit: "ADC",
        input: {
            requiredHours: 90,
            requiredDays: 45,
            performedHours: 15,
            performedDays: 52,
            startDate: "2026-06-12",
        },
        sheetDeadline: "2026-12-11",
        sheetDaysLeft: 122,
        sheetHoursLeftDisplay: 3,
    },
    {
        name: "VISHAL KUMAR",
        empId: "10023430",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 45,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-05-04",
        },
        sheetDeadline: "2026-09-03",
        sheetDaysLeft: 23,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "VIVEK KUWAR",
        empId: "10023503",
        unit: "PLR",
        input: {
            requiredHours: 60,
            requiredDays: 30,
            performedHours: 0,
            performedDays: 0,
            startDate: "2026-07-31",
        },
        sheetDeadline: "2026-11-29",
        sheetDaysLeft: 110,
        sheetHoursLeftDisplay: 12,
    },
    {
        name: "VIVEKANANDA DE",
        empId: "10004078",
        unit: "ACC+ACC(S)",
        input: {
            requiredHours: 210,
            requiredDays: 105,
            performedHours: 125.5,
            performedDays: 117,
            startDate: "2026-04-10",
        },
        sheetDeadline: "2027-06-09",
        sheetDaysLeft: 302,
        sheetHoursLeftDisplay: 84.5,
    },
];
