// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilkrqlxrqaelflslbdnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsa3JxbHhycWFlbGZsc2xiZG54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNTY5MTgsImV4cCI6MjA3NzkzMjkxOH0.YetOeCoBn5LlK8UBzUzq7ROi1uZ3bLksDkMzkGwl5rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});