// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variable. Ensure VITE_PUBLIC_SUPABASE_ANON_KEY is set in .env.local"
  );
}

// In production (Vercel), route all Supabase traffic through our backend proxy
// to avoid firewall blocks on *.supabase.co domains.
// In local dev, use the direct Supabase URL since Vercel serverless functions
// aren't available from `vite dev`.
const IS_DEV = import.meta.env.DEV;
const SUPABASE_URL = IS_DEV
  ? import.meta.env.VITE_PUBLIC_SUPABASE_URL
  : `${window.location.origin}/api/supabase`;

if (!SUPABASE_URL) {
  throw new Error(
    "Missing VITE_PUBLIC_SUPABASE_URL for local development."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});